HospitalRun/hospitalrun-frontend

app/styles/_sidebar_nav.scss

Fixes #122 by making the search button absolutely positioned so if scrollbars (or anything else) tighten up the layout, the search button doesn't drop down onto the next line.

Fix for breaking search button on sidebar nav

---

tests/README.md
tests/unit/components/nav-menu-test.js

by providing some subnav items required to execute the init method.  Useful tests and assertions to follow.

Got the nav-menu-test running

---

.gitignore
app/inventory/reports/controller.js

@jkleinsc, I think this is ready to go.

Inventory summary report

---

app/styles/_sign_in_screen.scss

Resolves #132
Used a horizontal translate transform equal to half of the computed modal (similar to what is being done for vertical alignment)

Adjust horizontal alignment of sign in modal

---

app/components/nav-menu.js
app/controllers/abstract-edit-controller.js
app/imaging/completed/route.js
app/imaging/completed/template.hbs
app/imaging/edit/controller.js
app/imaging/edit/route.js
app/imaging/edit/template.hbs
app/imaging/index/route.js
app/imaging/index/template.hbs
app/imaging/route.js
app/initializers/i18n.js
app/locales/en/translations.js
app/mixins/modal-helper.js
app/templates/components/patient-summary.hbs

-Added an initializer to inject the I18N service into all controllers, routes, and mixins
-Did not write any i18n-specific tests - don't have a lot of experience in how to automated test i18n, in this case knowing that the current tests didn't break when run with the 'en' locale is probably good enough? Would gladly write some if you have any suggestions.
-The Ember localization syntax can get kind of awkward sometimes, it doesn't feel very DRY. Take for example the subActions changes in app/imaging/route.js - you can't access the translation helper in the array because this isn't bound to the route , so you have to change it to a function. Not sure if there's a way around this, that method was recommended here: http://stackoverflow.com/a/33380796/265714
A couple of things I considered …

Address #277: Localization for Imaging Module

---

app/locales/en/translations.js
app/medication/completed/route.js
app/medication/delete/controller.js
app/medication/delete/template.hbs
app/medication/edit/controller.js
app/medication/edit/route.js
app/medication/edit/template.hbs
app/medication/index/route.js
app/medication/index/template.hbs
app/medication/return/controller.js
app/medication/return/route.js
app/medication/return/template.hbs
app/medication/route.js
app/medication/search/template.hbs

One thing I wanted to highlight is the 'searchStatus' parameter used in many of the index routes isn't easy to internationalize right now - because that same string is used for both display and is actually stored in the model - I think we'll have to switch to use category id: string mappings and translate those for the models?

Fixes #278: Localization for Medication module

---

CONTRIBUTING.md
README.md

For the couchDB instructions, I found it more clarifying to add where
the configuration scripts needed to be run.
Also some spelling corrections

Instruction clarification and spelling

---

app/appointments/delete/template.hbs
app/appointments/edit/route.js
app/appointments/edit/template.hbs
app/appointments/index/route.js
app/appointments/index/template.hbs
app/appointments/item/template.hbs
app/appointments/route.js
app/appointments/search/route.js
app/appointments/search/template.hbs
app/appointments/today/route.js
app/locales/en/translations.js

Appointments Section Translation

[TRANSLATION] Translated appointments section

---

app/styles/_base.scss

This adds a selector to highlight actionable areas by showing the pointer cursor for elements with the `data-ember-action` attribute.
This should probably be temporary, to help show where more specific classes could be added.  
Without the class
With the class

Action cursor

---

README.md

Updating the readme for better explanation of the linter.

Update docs to account for scss-lint

---

app/users/index/template.hbs

Fixes #415 .
- Switch table data displayName and name from Users in User's admin page
Old:
New:

Switch labels in user admin page

---

app/appointments/item/template.hbs
app/appointments/missed/controller.js
app/appointments/missed/route.js
app/appointments/missed/template.hbs
app/locales/en/translations.js
app/mixins/appointment-statuses.js
app/mixins/navigation.js
app/models/appointment.js
app/router.js
tests/acceptance/appointments-test.js
tests/unit/appointments/missed/route-test.js

Fixes #351 .
I didn't realize the other appointment routes already filter to the latest, so 'missed' doesn't require any filters.
I added a test, and modified the `createAppointment` helper function to accept params.
-

Adding 'missed appointments' tab

---

app/patients/search/route.js

Fixes # .
- Enabled patient search through their phone number.
Currently patient can only be searched with their id, firstname and lastname

Enabled patient search by phone number

---

app/imaging/completed/completed-list-item/component.js
app/imaging/completed/completed-list-item/template.hbs
app/imaging/completed/template.hbs
app/imaging/edit/template.hbs
app/imaging/index/imaging-edit-button/component.js
app/imaging/index/imaging-edit-button/template.hbs
app/imaging/index/requested-list-item/component.js
app/imaging/index/requested-list-item/template.hbs
app/imaging/index/template.hbs
app/styles/app.scss
app/styles/components/_imaging.scss

Fixes #362.
- Adds `Requested By` to Imaging **Requests** and **Completed** lists
- Refactors Imaging to use [components in blocks](https://github.com/DockYard/styleguides/blob/master/engineering/ember.md#use-components-in-each-blocks)
- Adds `Add Note` link to the **Requests** list items that don't have notes
- Adds `No Notes` and `No Results` to **Completed** list items that don't have either Notes or Results
---
`Add Notes` link:
`No Notes` and `No Results`

Add `Requested By` to Imaging

---

app/labs/completed/labs-completed-list-item/component.js
app/labs/completed/labs-completed-list-item/template.hbs
app/labs/completed/template.hbs
app/labs/edit/template.hbs
app/labs/index/labs-edit-button/component.js
app/labs/index/labs-edit-button/template.hbs
app/labs/index/labs-list-item/component.js
app/labs/index/labs-list-item/template.hbs
app/labs/index/template.hbs
app/styles/app.scss
app/styles/components/_labs.scss

Fixes #364 .
- Adds `Requested By` to Labs **Requests**, **Completed** and **Edit**
- Refactors Labs to use [components in blocks](https://github.com/DockYard/styleguides/blob/master/engineering/ember.md#use-components-in-each-blocks)

Add requesting clinician to Labs

---

script/bootstrap

- Add space to bootstrap script to prevent bower setup from being skipped

Add missing space to script/bootstrap

---

README.md

I assume a step was added between when the “Make” section was last
updated and now, so I corrected the step numbers that must be completed.

Corrected one of the step numbers in the "Make" section

---

app/components/nav-paging.js
app/styles/_layout.scss
app/styles/_temp_misc.scss
app/styles/app.scss
app/styles/components/_pagination.scss

- created a component stylesheet for pagination
- fixed the positioning of the pagination buttons
**Before:**
**After:**
Note: pagination button styles and markup still need improved, but going to address in another PR because it involves refactoring, and more thought around button strategy in general (related to #359).
Also, addresses #134.

Pagination button tweaks

---

app/locales/en/translations.js
tests/helpers/start-app.js

Stubs the translation function that do the translation and
throw an error if it is missing
uses deprecated api, happy to change but atleast it is only one
instance
All Feature tests must run startApp in the before each hook

Test for missing translations

---

package.json

no need for this to be a production dependency.
@jkleinsc unless you moved them on purpose so that we know about the regex dos

Move dependencies to dev dependencies.

---

app/invoices/edit/controller.js

Doesn't fix any particular issue just a small refactor i found while doing translations,
the rest of the translations will come in with invoices

Small refactor

---

app/locales/en/translations.js
tests/acceptance/invoices-test.js
tests/acceptance/pricing-test.js

I previously let `<strong>` tag in delete message through to master. after reading all delete strings this does not seem to be the standard so i removed the tags. 

remove <strong> from delete message

---

app/locales/en/translations.js
app/mixins/charge-actions.js
app/patients/socialwork/expense/controller.js
app/patients/socialwork/family-info/controller.js
app/procedures/charge/template.hbs
app/procedures/edit/controller.js
app/procedures/edit/template.hbs
app/visits/edit/controller.js

Found a pile of translation bugs, fixed them in this pr.

Translation bugs

---

app/procedures/edit/controller.js

Fixes #526 .
- The add button was hidden on this screen because the updateCapability was 'add_charge" in the procedures edit controller. I changed it to 'add_procedure' - this matches other controllers that appear in the visit (add_medication is used for the medications edit controller, for example).

#526: Use add_procedure for procedure edit updateCapability

---

app/appointments/search/template.hbs
app/components/charge-quantity.js
app/components/loading-message.js
app/components/modal-dialog.js
app/invoices/edit/template.hbs
app/locales/en/translations.js
app/locales/es-CO/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/patients/edit/template.hbs
app/patients/notes/template.hbs
app/templates/components/edit-panel.hbs
app/templates/components/patient-summary.hbs
app/templates/components/take-photo.hbs
app/templates/item-charges.hbs
app/templates/sidebar_nav/search.hbs
app/visits/delete/template.hbs
app/visits/edit/template.hbs
app/visits/procedures/delete/template.hbs
app/visits/vitals/delete/template.hbs
app/visits/vitals/edit/template.hbs

OK so this is quite a few translation changes :)
- Refactored visits, to look a bit like the rest.
- translated components, parrtials, print.invoice
- fixed a few bugs
i have a note saying i must go through invoices aswell, would like to discuss my 2 refactor issues first.
- https://github.com/HospitalRun/hospitalrun-frontend/issues/551
- https://github.com/HospitalRun/hospitalrun-frontend/issues/547

Translations

---

app/components/charge-quantity.js
app/locales/en/translations.js
app/templates/components/charges-by-type-tab.hbs
app/templates/components/price-list.hbs
app/templates/components/quantity-calc.hbs
app/templates/components/quantity-conv.hbs
app/templates/components/take-photo.hbs

Translates components files. i refactored take-photo translations to match new style
convention discussed here
https://github.com/HospitalRun/hospitalrun-frontend/issues/557

Translate components

---

app/templates/components/edit-panel.hbs
app/templates/components/modal-dialog.hbs
app/users/index/template.hbs

Fixes #360.
- Moved the primary action button to the right
- Fixed the appearance of the delete button in the user listing

Adjustments to the primary action and delete buttons

---

README.md

"You should see the following screen:" gets cut off at "You should see" with the screenshot in between, and "the following screen:" shown to the bottom left of this screenshot.
Adding an extra newline fixes the issue.

README Fix text flow issue around screenshot

---

app/components/type-ahead.js
app/styles/_temp_misc.scss

Fixes #519 Medication/inventory typeahead issues 
- Typeahead now displays a maximum  of 10 options by adding limit in typeahead.js. Adding more than 10 appears to make the acceptance tests timeout
- Typeahead now has a maximum height of 110px and displays a vertical scrollbar 

Added scrollbar and more options in typeahead

---

app/components/sortable-column.js
app/styles/_temp_misc.scss
app/templates/components/sortable-column.hbs

Fixes #328 
- add new icon for default state of sortable-column
- add 'sortable-column' classname to sortable-column component
- add a new css rule to use the pointer cursor for .sortable-column class

Updating sortable columns to have sorting icon and updated cursor

---

Dockerfile
README.md
script/initcouch.sh

Create docker image for hospital run front-end
- Added a dockerfile to create the hospital run front-end image
- Able to link couch database to the container
- Modified script files to support this change
- Added instructions to the readme.md

added dockerfile

---

app/appointments/edit/controller.js
app/appointments/search/controller.js
app/mixins/visit-types.js
app/patients/reports/controller.js
app/visits/edit/controller.js

Fixes #627 
- Fixes the typo that was causing the visitTypesList to not be computed properly.
- Add volatile to the dependent property of visitTypesList (see app/mixins/visit-types.js).  It looks like being dependent on a computer property doesn't quite work as any subsequent updates to the underlying data is not firing the observers (i.e. the mixin functions).  

Issue 627: Fix visit types list not refreshing.

---

README.md

No previous issue open about this PR.
This conversation was had with @jglovier IRL.
- Adds couchdb badge to the README
- [![CouchDB](https://img.shields.io/badge/couchdb-2.0-green.svg)](http://couchdb.apache.org/)
- Move experimental section of the README to the end
- Add a step 8 to the install section (about CouchDB)
- Primarily reduces confusion around errors in the CLI around CouchDB not starting

Adding step #8 to README

---

app/admin/lookup/controller.js
package.json

Fixes part of https://github.com/HospitalRun/hospitalrun-frontend/issues/540.
- Keyboard ctrl-S or cmd-S is same as clicking Update button, see gif
- Overrides Chrome cmd-S keyboard shortcut
- TODO: Next step would be to implement on all Update and Save buttons
Pair: @alychloe

Keyboard ctrl-S or cmd-S is same as clicking Update button

---

app/inventory/batch/template.hbs
app/inventory/request/template.hbs
app/styles/components/_form_styles.scss

Fixes #322.
-Hid redundant labels using “sr-only” class.
-The checkbox ended up where the label used to be so I added a class of
“checkbox-label-space” that can be used where that comes into play.
gif:
http://recordit.co/qtt0q8Xwt7

Hid checkbox labels

---

app/mixins/patient-id.js
app/patients/edit/controller.js

The suggested patient ID keeps getting incremented even if we cancelled the new patient form. This problem should be related to issue #485 and more info can be found in https://github.com/HospitalRun/hospitalrun-frontend/issues/485#issuecomment-249384870.
I try to solve the problem by saving the _current_ sequence rather than the next available one. We start checking from the current sequence when preparing a new patient form. The value would be incremented and saved only if it has already been taken. So, no matter how many times we click the cancel button, the suggested patient ID would always be the same.
Please correct me!

Fixes #485: Suggest next patient ID based on the largest number used

---

README.md

No previous issue about this pull request
I just started looking at this project and while I was going through the install section I was a little bit confused by the formatting of the Create Admin User section of the Install section in the README.
I am sorry that I didn't make an official issue prior to this, but it is a pretty minor change that I just wanted to add in to make the README a little bit clearer for new users.
**Proposed Changes**
Change format of part IV of step 6 from this:
to this:
Changed README.md at part IV in step 6 of the Install section. The README seemed like it was supposed to format this step into two different sections, one for users running CouchDB 1.x and one for 2.x. However, I think that no line break occurred that …

Update Format of README Section

---

app/medication/return/template.hbs
app/procedures/medication/template.hbs
app/templates/inventory-basic.hbs

As an addition to PR #668, I converted the `em-input` helper to `number-input` for some more numeric form fields.

Use `number-input` for more numeric fields

---

app/components/edit-panel.js
app/mixins/edit-panel-props.js

Fixes #719 .
- Added action 'cancelAction' in component edit-panel.js 
- Removed all instances of cancelAction from mixin edit-panel-prop.js
- While adding a new user in the user listing, if a person fills in the details and clicks Cancel, that particular user won't be visible in the user listing on the index page of Users.

Bug fix for add user cancel error

---

app/components/custom-form.js
app/components/role-select.js
app/controllers/navigation.js
app/mixins/charge-route.js
app/mixins/navigation.js
app/mixins/pagination-props.js
app/mixins/patient-id.js
app/mixins/setup-user-role.js
app/models/inventory.js
app/patients/edit/controller.js
app/patients/notes/controller.js
app/routes/application.js
app/services/config.js
app/services/database.js
app/utils/item-condition.js
tests/acceptance/admin-test.js
tests/acceptance/patients-test.js
tests/helpers/authenticate-user.js
tests/helpers/run-with-pouch-dump.js
tests/integration/components/inventory/rank-select-test.js

`const` -> `let` (inside modules)
Part of #732.

[Cleanup] eslint `ember-suave/no-const-outside-module-scope`

---

app/admin/query/controller.js
app/components/charge-quantity.js
app/components/date-input.js
app/components/take-photo.js
app/models/inv-location.js
app/models/invoice.js

`//Comment` -> `// Comment`
Part of #732.

[Cleanup] eslint `spaced-comment`

---

app/models/allergy.js
app/models/patient.js

Addresses #234 .
- Added Allergy model
- Added hasMany Allergy relation to Patient
Happy Hacktoberfest! 
Taking an initial shot at this model. I assume it'll probably need changing. :) Not sure how many other allergy code types are out there or if you'd rather just pick a single system. Just did some initial googling around at allergy coding and found references to both of these.
I am assuming here that the data for these allergies would be seeded in the DB. Although, some UI for adding (or maybe importing?) new allergies is probably worth considering too?

Patient allergies

---

app/styles/components/_sidebar_nav.scss

The nav spacing is a little big for all the things that we have in the nav, and adding more items will only compound this problem. This PR tightens up the nav a little so less scrolling is required (especially on smaller screens).
- Reduce vertical nav spacing
- Reduce size of icons
**Screenshots:**
| Before | After |
|---|---|
| <img width="1275" alt="screenshot 2016-10-22 18 46 33" src="https://cloud.githubusercontent.com/assets/1319791/19623026/e350a596-9887-11e6-82be-26f6fcf59d90.png"> | <img width="1276" alt="screenshot 2016-10-22 18 45 24" src="https://cloud.githubusercontent.com/assets/1319791/19623023/bc54a0c8-9887-11e6-9b98-3ce6c2b66969.png"> |

Tighten up app nav spacing

---

app/appointments/search/route.js
app/components/custom-form.js
app/components/image-upload.js
app/components/price-list.js
app/components/quantity-calc.js
app/components/role-select.js
app/components/take-photo.js
app/helpers/date-format.js
app/inventory/reports/controller.js
app/patients/notes/controller.js
app/pricing/edit/controller.js

`let brand = car.brand;` -> `let { brand } = car;`
Part of #732.

[CLEANUP] eslint `ember-suave/prefer-destructuring`

---

tests/helpers/authenticate-user.js

`{'foo': 'bar'}` -> `{ 'foo': 'bar' }`
Part of #732.

[CLEANUP] eslint `object-curly-spacing`

---

app/adapters/application.js
app/controllers/abstract-edit-controller.js
app/services/filesystem.js

`}else {` -> `} else {`
Part of #732.

[CLEANUP] eslint `keyword-spacing`

---

app/components/date-input.js
app/mixins/dob-days.js
app/mixins/inventory-locations.js
app/services/database.js
app/serviceworkers/pouchdb-sync.js
app/utils/pouch-views.js

`+` should be on the new line instead of end of previous line
Part of #732.

[CLEANUP] eslint `operator-linebreak`

---

README.md

Adds a section to the README about running the tests.

Update docs with info about how to run the tests

---

.eslintrc.js

Fixes: part of https://github.com/HospitalRun/hospitalrun-frontend/issues/732
Relates to: https://github.com/HospitalRun/hospitalrun-frontend/pull/770 cc @btecu 
- Since many of the rules outlined in https://github.com/HospitalRun/hospitalrun-frontend/issues/732 aren’t part of eslint recommended https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/config/recommended.js, I suggest adding the rules to the `eslintrc.js`, so that they are enforced as they are fixed.
- Re: http://eslint.org/docs/rules/object-curly-spacing
Why? I just realized my fork was terribly out of date when I started looking at https://github.com/HospitalRun/hospitalrun-frontend/issues/732 recently. I have previously used ember-suave, am just getting started with …

Make eslint object-curly-spacing rule enforced

---

app/routes/abstract-module-route.js

`obj.foo.apply(obj, args)` -> `obj.foo(...args)`
Part of #732.

[Cleanup] eslint `prefer-spread`

---

app/appointments/search/template.hbs

Fixes untracked self-reported issue.
Fixed a small typo I stumbled upon while working on the calendar feature, with visible effects on the end-product.

Fix 'calss' typo in appointment search template

---

app/authenticators/custom.js
app/inventory/barcode/controller.js
app/mixins/progress-dialog.js

`new report()` -> `new Report()`
Part of #732.

[Cleanup] eslint `new-cap`

---

app/router.js

This is a code style improvement with no issue associated.
- Remove unnecessary `{ resetNamespace: true }` for top-level routes.
The routes declared directly beneath `Router.map` are already top-level, so the reset is unnecessary.
This has the added benefit of removing some visual cruft, because the few `resetNamespace`s left are actually meaningful, making visual parsing easier, as well as grepping.

Removes unnecessary `resetNamespace`s

---

app/components/quantity-conv.js
app/models/inv-purchase.js
app/models/inventory.js
tests/acceptance/inventory-test.js

Fixes #824.
- Updated inventory model to not allow negative numbers.
- Updated inv-purchase model to not allow negative numbers.
- Updated quantity-conv.js to consider negative quantities as an invalid number.
- Added an acceptance test to make sure items with negative quantities cannot be added.
- UI notifies when quantity is negative

#824 Update inventory quantity to not allow negative numbers, acceptance test added

---

tests/unit/utils/select-values-test.js

- Add unit test for select-values
Test aligns with current behavior if non-array value is passed in as the
first argument.

Add unit test for select-values

---

tests/unit/models/line-item-detail-test.js

- Add model unit test line-item-detail amountOwed

Add model unit test line-item-detail amountOwed

---

tests/unit/models/appointment-test.js
tests/unit/models/billing-line-item-test.js

- Add basic validation model unit tests for billing-line-item
- Add basic validation model unit tests for appointment

Add model unit test billing-line-item appointments

---

app/inventory/reports/template.hbs
app/patients/reports/template.hbs
tests/acceptance/inventory-test.js
tests/acceptance/patients-test.js

Fixes #851 
- Patients -> Reports and Inventory -> Reports export gives a file name with report name and date by using exactly the report title.

Report export name

---

app/components/inventory-typeahead.js
app/locales/en/translations.js
app/models/inv-location.js
tests/unit/models/inv-location-test.js

- Add `locationNameWithQuantity` translation for InventoryLocation model
- Add translation for items in inventory-typeahead component select list
- Add en translation for `inventory.labels.availableQuantity`
- Add model unit test for inv-location

Add availableQuantity translation

---

tests/unit/mixins/can-edit-requested-test.js
tests/unit/mixins/date-format-test.js

- Add unit mixin test for `date-format`
- Add unit mixin test for `can-edit-requested`

Add unit mixin tests for date-format and can-edit-requested

---

tests/unit/mixins/appointment-statuses-test.js

- Add unit mixin test appointment-status AppointmentStatuses
New creation of mixin unit test section. Following format of util with
the exception of leaving "Unit | Mixin" singular. All others appear to
be in the singular format except "Unit | Utils

Add unit mixin test mixins/appointment-statuses AppointmentStatuses

---

app/mixins/medication-details.js
tests/unit/mixins/medication-details-test.js

Fixes Issue with promise not being detected and defines issues with return values
- Add mixin unit test for `MedicationDetails`
- Define issue where `getMedicationPrice` and `getMedicationName` do
not return a value on first retrieval
- Add documentation explaining issue with return values
- Fix error on `getMedicationPrice` if attribute is not a promise
- Remove duplicate calls to `get` when a promise is detected
Not changing methods to use `Ember.RSVP.Promise` as anything that uses
those methods would currently not be setup to handle a returned
promise. This may want to be adjusted in the future.

Define issues with MedicationDetails and tests

---

bower.json
ember-cli-build.js
tests/unit/mixins/dob-days-test.js

- Add mixin unit tests for dob-days
- Add bower devDependencies for `timekeeper` library to handle
'new Date()`
- Import `timekeeper` dependency when build environment is "test"

Add mixin unit tests for dob-days

---

tests/unit/models/proc-charge-test.js

- Add model unit test for proc-charge

Add model unit test for proc-charge

---

tests/unit/mixins/location-name-test.js

- Add mixin unit tests for location-name

Add mixin unit tests for location-name

---

app/models/photo.js

Closes #881
- Remove `downloadImageFromServer` from photo model
Function will throw an error if used and is not currently used in code
base

Remove downloadImageFromServer from photo model

---

tests/unit/mixins/patient-name-test.js
tests/unit/models/patient-test.js

- Add mixin unit test for patient-name
- Add unit model test for patient

Unit test patient model mixin

---

app/models/inventory-batch.js
tests/unit/models/inventory-batch-test.js

- Define incorrect behavior of `InventoryBatch.haveInvoiceItems()` in
model unit test
`haveInvoiceItems` returns `true` if `invoiceItems` is empty. This
should likely be reversed or method name should change.

Define Incorrect Behavior of haveInvoiceItems

---

app/controllers/abstract-edit-controller.js
app/locales/en/translations.js
tests/unit/controllers/abstract-edit-controller-test.js

- Add abstract-edit-controller unit tests
- Add translations for `showDisplayDialog` action
- Add translations for `update` action on exceptions and failed promise

Add abstract-edit-controller tests and Add Translations

---

app/controllers/abstract-report-controller.js
app/locales/en/translations.js
package.json
tests/unit/controllers/abstract-delete-controller-test.js
tests/unit/controllers/abstract-paged-controller-test.js
tests/unit/controllers/abstract-report-controller-test.js

- Add unit tests for controller abstract-delete-controller
- Add dependency(devDependency) for ember-sinon-qunit for use in
stubbing methods for proper test coverage
- Update documentation with `@todo` about possible unintended behavior
of the `sortByKey` action
The tests in this commit preserve the behavior as implemented. It is
possible that `sortByKey` should also set `nextStartKey` and `startKey`
to `null` as well.
- Add translations for `_notifyReportError` in
abstract-report-controller
- Add unit test for `_notifyReportError`
- Add translations for `_setReportTitle` in abstract-report-controller
- Add unit tests for `_setReportTitle` with translations
- Add unit tests for abstract-report-controller
- Add unit tests from …

Add abstract controller unit tests and translations

---

app/controllers/abstract-paged-controller.js
tests/unit/controllers/abstract-paged-controller-test.js

- Fix `sortByKey` not clearing all properties in
abstract-paged-controller
- Add `firstKey` and `nextStartKey` to be set to `null`
Based upon discussion from #900 

Fix sortByKey not clearing all properties

---

app/models/allergy.js
app/models/diagnosis.js
app/models/patient-note.js
app/models/patient.js

Re-write of the patient model, using the ember style guides from Dockyard

Modified patient model, using ember style guides

---

app/controllers/index.js

`Ember.on` and `Ember.computed` are currently preferred over the prototype extensions `Function.prototype.on` and `Function.prototype.property`.
- Replaces `Function.prototype.on` with `Ember.on`
- Replaces `Function.prorotype.property` with `Ember.computed`

Updates code to current practices

---

app/locales/en/translations.js
app/locales/pt-br/translations.js
app/patients/edit/controller.js

Patient types was not using localization.  This PR refactors patient types to use i18n

Refactor patientTypes to use i18n

---

app/appointments/calendar/template.hbs
app/appointments/edit/template.hbs
app/appointments/index/template.hbs
app/appointments/search/template.hbs
app/appointments/theater/template.hbs
app/locales/en/translations.js

Partly Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/547
- Starts moving translations to format defined in the issue
i will clean up the old keys when the migration is complete

Refactor appointment translations

---

README.md

hospitalrun-frontend
Fixes no issue already created.
Change proposed in this pull request:
- Fix typo on README.md ## Running with Docker section -> from `cd hosptialrun-frontend` to `cd hospitalrun-frontend`

Fix typo on README.md ## Running with Docker section

---

.github/CONTRIBUTING.md
README.md

Fixes: Consolidation and updating of documentation about linters used in the project.
- Removed outdated linter information , about SCSS, from main README
- Removed outdated information about Ember Suave etc from top of CONTRIBUTING guide.
- Added to existing documentation in Linter section of CONTRIBUTING guide - including external links to documentation about eslint-plugin-ember-suave and ember-template-lint.

Updating documentation about linters.

---

app/admin/print-header/controller.js
app/admin/print-header/route.js
app/admin/print-header/template.hbs
app/locales/en/translations.js
app/mixins/navigation.js
app/router.js
tests/acceptance/admin-test.js

Fixes #790 
- Create a new configuration screen for header printing
- Add translation needed for header-print screen
- Add "Print Header" navigation under Administration tab
cc @jkleinsc

Customizable print header

---

tests/acceptance/patients-test.js

Fixes #699 .
- Add acceptance test for patients.admitted route.

add patient admitted test.

---

app/admin/custom-forms/index/route.js
app/admin/lookup/controller.js
app/appointments/delete/template.hbs
app/imaging/delete/template.hbs
app/inc-category/delete/template.hbs
app/inc-category/edit/controller.js
app/incident/delete/template.hbs
app/incident/edit/controller.js
app/incident/note/delete/template.hbs
app/inventory/delete/template.hbs
app/invoices/delete/template.hbs
app/labs/delete/template.hbs
app/locales/en/translations.js
app/medication/delete/template.hbs
app/patients/delete/template.hbs
app/pricing/delete/template.hbs
app/procedures/edit/controller.js
app/users/delete/template.hbs
app/visits/delete/template.hbs
app/visits/procedures/delete/template.hbs
app/visits/vitals/delete/template.hbs
tests/acceptance/users-test.js

Fixes #543.
- Added 3 standard delete message in translation file.
- Replace "delete" message in multiple template files with new standard message.

Refactor delete message translation

---

app/admin/custom-forms/edit/controller.js
app/labs/edit/route.js
app/labs/edit/template.hbs
app/locales/en/translations.js

Fixes #65 
- Add custom form for lab's report.

add custom form for labs

---

tests/acceptance/appointments-test.js

Fixes #690 
- add appointments.today test for appointment route

add appointment today test

---

.dockerignore
docker-compose.yml

Fixes #980 
- reduce the steps to build and run the application .
- Added ".dockerignore" file .
- Added "docker-compose.yml" for necessary port mapping, linking with couchdb and running the couchdb.
- Command to run docker-compose "docker-compose up".
**Work in progress**
* Compile ember app to use production environment
cc @jkleinsc @jglovier @tangollama

[WIP] Docker Compose Added

---

app/locales/en/translations.js

Fixes self-reported issue.
- a minor fix for two labels that displayed incorrect text.

Two translated labels fixed

---

README.md

A contributor in our Slack channel noticed that the installation instructions are confusing for contributors, because we specify that you should clone this repo, when in fact if you are a contributor without write access to this repo (basically any new contributor) you will need to fork first, and then clone your fork.
This PR adds some copy to clarify that. Also adds a table of context because this README is getting super long (and should probably be refactored into better docs).

Clarify in README whether installation instructions whether to clone or fork

---

app/patients/edit/controller.js
app/patients/edit/template.hbs

Fixes #377 
- Take out modal
- Show inline alert above button
- Hide inline alert after 3000ms
@billybonks @jglovier

Move modal alert to inline

---

.github/CONTRIBUTING.md
app/locales/en/translations.js
package.json
script/translation/sync.js

Fixes #862
- Script to automate populating non-English translations with the keys existing in English translations and reorder the keys in translation file by alphabetic order
- Actually go reorder the keys in English translation file

Automate syncing translation files

---

app/inventory/adjust/controller.js
app/inventory/reports/controller.js
app/locales/en/translations.js
app/mixins/inventory-adjustment-types.js
tests/unit/mixins/inventory-adjustment-types-test.js
tests/unit/models/inv-request-test.js

Fixes #390.
There are two issues, which are related:
1. Localization of drop-down
Added translation keys to app/mixins/inventory-adjustment-types.js. So now the drop-down list for Adjustment Types is translated. Added English translations. I didn't update the files for the other languages - I'm not sure of the process for getting translation text in multiple languages - let me know if you'd like me to do something more about that.
2. Localization of the 'submit' button.
In app/inventory/adjust/controller.js I use the the Transaction Type to find a localized Adjustment Type name.

Address issue #390, Adjustment types for inventory need to be localized

---

README.md

Update README.md for typos and added links for PouchDB, Docker.
Does not fix any specific open issue. 
- Typos
- Docker link
- PouchDB link

Update README.md for typos and added links

---

.github/CONTRIBUTING.md
package.json

Fixes #1066 
- Update instruction to run translation-sync script to include missing dependency
- Use `&&` instead of `;` for compatibility with Windows

fix translation-sync instruction and script

---

ember-electron/electron-forge-config.js

Fixes #1075 - Create the electron windows 64-bit download/install
- [updated icon path in winstaller config to mitigate windows build error]

updated winstaller config icon path for error free windows build

---

script/setupcloud9

Fixes #1089 .
- Adds a setup script to ./script specifically for the cloud9 development environment
- The script works through the quirks specific to cloud9 to ensure that the app will run correctly and the tests will not give false errors
- To test this script, setup a workspace as described in [the top section of this wiki document](https://github.com/HospitalRun/hospitalrun-frontend/wiki/Optional:-Cloud9-Development-Environment). After the workspace is created, run:  `source ./script/setupcloud9` from the shell window. When the script completes the environment should be setup correctly.
**Additional Notes**
I am a cloud9 user that recently started exploring the hospitalrun project. Initially, I ran into some frustrating issues with test …

Add cloud9 setup tool

---

README.md

Previously, lines were ended in a variety of ways. Most significantly,
the use of periods and blanks was mixed. I've added periods and colons
to appropriate locations.
-    Change all line endings to full stops or colons (mainly addresses lists).

Normalize line endings within readme

---

app/appointments/search/template.hbs
tests/acceptance/appointments-test.js

Addresses #689 
- This PR adds acceptance test for appointment searches based on start date
I plan to write more tests for the other searchable appointment attributes.  Submitting this now for initial feedback.

First working acceptance test for appointments/search path; ensures only the correct appointment is displayed based on its start date

---

.github/CONTRIBUTING.md

This PR improves the Contributing doc by adding some additional guidelines for how to use our Slack channel effectively.

Improve contributing doc

---

README.md

I arrived here without context, and nowhere did the readme actually say what HospitalRun is.
- Add a few details to the top of the readme to explain what HospitalRun is.

Readme: Add HospitalRun link and brief description

---

README.md

Added 1 question into FAQ.
-Fixed docker hyperlinks in table of contents. Acessing docker-composed was not updated in the TOC and there is a case sensitivity issue from a previous commit causing the below titles to not work. Can replicate by trying to click on the titles at https://github.com/HospitalRun/hospitalrun-frontend#table-of-contents
: 
Accessing HospitalRun with Docker Toolbox
Accessing HospitalRun with Docker
Fixes #1101 
Just to get the ball rolling and fixed two hyperlink issues.

Added FAQ and fixed broken docker links

---

app/locales/de/translations.js
app/locales/es-co/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/locales/pt-br/translations.js
app/locales/ru/translations.js
app/locales/tr/translations.js
app/locales/ur/translations.js
package.json

Complements/Addresses #1094.
- Added language translations for all available languages
I am a bit confused how there are two dropdowns for spanish and spanish (colombian). As far as I can tell the languages are pretty much the same and differ in dialect/slang. Would love some clarification. 
https://www.quora.com/What-are-the-major-differences-between-Colombian-Spanish-and-Spanish-from-Spain
https://www.lonelyplanet.com/thorntree/forums/americas-mexico/mexico/how-different-is-mexican-spanish-to-colombian-spanish
Also after reviewing my commit files, should I not have included my package-lock.json file (17k lines of code...)? I couldn't find anything about it in the contributing guidelines. Edit: I have now removed …

Added missing languages translations in the dropdown

---

app/styles/components/_sidebar_nav.scss

Fixes #1134.
- Fixed css styling for logout class
This code references a class of logout, which is actually not defined anywhere (that I could find anyway). 
``` <a href="#" class="logout" {{ action 'invalidateSession' }}>{{t "navigation.actions.logout"}}</a>```
**Previously**
**After**
In the after pics, the hyperlink to logout is only accessible via clicking the text "log out"

Fixed Logout UX issue where users could logout accidentally

---

app/patients/reports/template.hbs

Fixes #1147 .
-Added `maxDate` property to date-picker which seemed to be missing for this template. All other reporting templates appear to be a-ok from what I can tell.

fixed max date property on total patient day reports

---

.github/CONTRIBUTING.md

This pull request doesn't fix an issue explicitly, but addresses a conversation had in Slack over Slack etiquette from here https://hospitalrun.slack.com/archives/C02BT7ZBK/p1505380410000243
This updates the advice about what commands can and should be used, with the usage of `@everyone` and `@channel` being discouraged, and `@here` being deemed acceptable as it only notifies people currently active on Slack, as per https://get.slack.help/hc/en-us/articles/202009646-Make-an-announcement

Slack mention etiquette

---

README.md

Prevent warnings displayed when installing current version.
If current version is installed, the following yellow `WARNING` is displayed after execution `make serve` command.
`WARNING: Node v8.5.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js`
- Removing the fear that may not be performed stably.
- I added a description about recommended version of Node.js

Add a description about recommended version of Node.js

---

app/patients/edit/template.hbs
tests/acceptance/appointments-test.js

Adds tests to increase code-coverage on appointments/edit controller.js to 100% route.js to 96% . Not sure what test would be needed to test line 70 in route.js.
To run code coverage: `ember install ember-cli-code-coverage@0.3.12` version 0.4 seems broken.
Then run `COVERAGE=true ember test` and open hospitalrun-frontend/coverage/index.html to see the results.
- Added attributes to appointment buttons in template for selecting in testscript
- Added appointment test which changes the type of appointment
- Added appointment test created from patient edit screen

added 2 appointment tests and 2 test-attributes to template

---

README.md

- Fix typo, correct term is "most"

Fix typo in README(not "mose", "most" is correct)

---

app/admin/custom-forms/field-edit/controller.js
app/admin/custom-forms/field-edit/template.hbs
app/locales/en/translations.js
app/templates/components/custom-form.hbs
tests/acceptance/custom-forms-test.js

Closes #1140 
- Added Header value to the Custom Forms Add Field drop-down
- When user selects the header option, it shows the Add Value section
- Have limited how many values a user can add to 1 for the header option, the rest have no limit still
- Displays the new header value in the form

Added in Header type value in Custom Forms

---

README.md

Fixes self-reported issue.
I run and always have into this issue with a clean install of Ubuntu and following the instructions, which I think is a common setup. I always have to take the mentioned step to get `bootstrap` to execute successfully.
I think that adding this to the README will save others' time, in the absence of a more permanent fix.
As for a more permanent fix:
How about taking `bower install` out of the bootstrapping script if we're not okay with permanently adding the `allow-root` flag?
<hr/>

Add possible fix for `bower install` when root to README

---

package.json
yarn.lock

Fixes #1155.
- Remove from npm packages.json
- Remove from yarn yarn.lock
This one is quite simple, although I don't understand why there is a yarn.lock file but nothing mention yarn in the install documentation.

Remove deprecated npm crypto module dependency. Close #1155

---

README.md

Fixes self-reported issue.
* Turns three notes in the bootstrap section into two: the one that was deleted contained information that was relevant inside other, existing notes.
* Moves the "Windows users must run with Cygwin" note above the root issue for bower, as it is of greater importance (at least from my perspective as a Windows user who doesn't use Cygwin all that much).
<hr/>
Sorry about the double PR for the Readme, I completely missed the surroundings of the root & bower install note back in my first PR. I just fully read the instructions and the notes section as it was proved confusing and messy because it discussed the same things in multiple notes.

Reduce number of notes in README

---

app/inventory/edit/template.hbs

Addresses #333.
- Allows a location to be shown and adjust even if the quantity is 0
- A location can be deleted (archived set to true) to remove any unneeded locations
**Base Inventory Edit Screen**
**Changes that I have made**

333-inventory-let the user to adjust the location/ archive a location

---

app/locales/de/translations.js
app/locales/en/translations.js
app/locales/es-co/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/locales/hi/translations.js
app/locales/hindi/translations.js
app/locales/pt-br/translations.js
app/locales/ru/translations.js
app/locales/tr/translations.js
app/locales/ur/translations.js

Fix missing language error for language dropdown menu in navigation bar
Fixes #1276 .
- translations.js for each language under locales folder

Fix missing language error for language dropdown menu in navigation bar

---

app/mixins/dob-days.js

address #1268 
- perform date comparison using UTC time to pass dob-days phantomJS tests

#1268 need to use UTC in dob-days to pass tests in different timezones

---

app/components/language-select.js
app/locales/de/translations.js
app/locales/en/translations.js
app/locales/es-co/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/locales/hi/translations.js
app/locales/pt-br/translations.js
app/locales/ru/translations.js
app/locales/tr/translations.js
app/locales/ur/translations.js

Fixes part of #1245
- Make language names in dropdown the same regardless of locale. This is useful so that users can find their preferred language easily regardless of what is already chosen.

Make language names in dropdown the same regardless of locale

---

Dockerfile
docker-compose.yml

Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/1293.
- Update Dockerfile to use `node:6-alpine` instead of `ubuntu`
- Update Dockerfile to install `npm` dependencies first, decreasing build time. (NOTE: should also include bower as well, but bower is deprecated and will need to be fixed anyway).
- Update `docker-compose.yml` to wait for `couchdb` to be launched before launching hospitalrun, prevent errors.

Update Docker Compose and Dockerfile

---

package.json

Closes #1125 #1260.
- pouchdb is on its latest
- rebased -> no merge conflict

chore(package): update pouchdb to version 6.3.4

---

ember-cli-build.js

Fixes the deprecation message: **DEPRECATION: Putting the "includePolyfill" option in "babel" is deprecated, please put it in "ember-cli-babel" instead** which comes up on build, by moving the option includePolyfill to the 'ember-cli-babel' object as per [here](https://github.com/babel/ember-cli-babel#polyfill).
---

Change "includePolyfill" option position

---

app/components/expand-text.js

There was extraneous code that was causing the Notes field to fail and kill events on the page. This change fixes that.
Fixes #[replace brackets with the issue number that your pull request addresses].
- removed unneeded code
- remove call to getBoundingClientRect in the didInsertElement that was causing error

Found a bug in expand text component.

---

.gitignore
app/appointments/edit/template.hbs
app/appointments/item/template.hbs
app/imaging/edit/template.hbs
app/invoices/edit/template.hbs
app/labs/edit/template.hbs
app/medication/edit/template.hbs
app/patients/edit/template.hbs
app/patients/imaging/template.hbs
app/patients/labs/template.hbs
app/patients/medication/template.hbs
app/visits/edit/template.hbs

Fixes #496
Add `class="clickable"` to several clickable elements that were missing the pointer cursor on hover.
Updated the following areas of the app:
- patient tabs
- appointments
- imaging
- invoices
- labs
- medication
- visits

496 : add "clickable" css class to editable objects

---

app/locales/es/translations.js
app/locales/fr/translations.js

Fixes some translations in french and spanish and adds some new translations.
While going through french translations, I fixed mistakes that changed the original meaning of the string. For example, "noon" and "midnight" were inverted. Also the case for the `totalMontlyExpense` translation : it was translated as income. And finally, "confinement" was translated as childbirth. 
I fixed these errors, but I don't know if it's really a good idea, because it can be really disruptive for the french speaking users. What do you think?

Improving french translations

---

app/styles/components/_patient_summary.scss

Fixes #1395
- Removed width limit from name field label (from patient summary scss form) because "nombre" in Spanish has 6 characters and it overlaps with the name entered.
-This is how it looks with the fix

removed fixed width from ps-info-label

---

app/locales/de/translations.js
tests/integration/components/language-select-test.js

- languageName for german should be `Deutsch` instead of `Deutsche`
sources for non native speakers: [1](https://www.google.de/imgres?imgurl=https%3A%2F%2Fcdn6.aptoide.com%2Fimgs%2F2%2F9%2F4%2F294dc522f8d99ba19cf93e06491a9c4f_screen.png%3Fh%3D464&imgrefurl=https%3A%2F%2Fwhenair-inc-locale-language.de.aptoide.com%2F&docid=-wEsggtPZZq4VM&tbnid=oglazXJOswA4iM%3A&vet=10ahUKEwjowMLDxoraAhXLI1AKHWP7CcoQMwg8KAAwAA..i&w=261&h=464&itg=1&bih=949&biw=1916&q=spracheeinstellungen&ved=0ahUKEwjowMLDxoraAhXLI1AKHWP7CcoQMwg8KAAwAA&iact=mrc&uact=8), [2](https://www.google.de/imgres?imgurl=http%3A%2F%2Fwww.mynfon.com%2Ffileadmin%2F_processed_%2Fcsm_sprache_9521c9543c.png&imgrefurl=http%3A%2F%2Fwww.mynfon.com%2Fhandbuecher%2Fsoftware%2Fwindows%2Fhandbuch-nsoftphone-p …

fix(locales/de): languageName

---

app/mixins/navigation.js
app/styles/components/_sidebar_nav.scss

Fixes `nav-sidebar` highlighting of sub and main routes.
Before: #1401 
Now:
Closes: #1401 

1401 highlight current route

---

.npmrc
package.json
yarn.lock

Fixes #1413. This would also allow PR #1314 to be closed. Those test failures no longer fail on master.
- bump ember-sinon-qunit to latest

bump ember-sinon-qunit, disable package-lock.json

---

tests/.eslintrc.js
tests/helpers/run-with-pouch-dump.js

This PR refactors the `runWithPouchDump()` test helper function to use async/await instead of implicit promise chaining. The goal of this PR is to allow the use of async functions in the tests too, which a follow-up PR will introduce later.

Simplify ` runWithPouchDump()` test helper

---

package.json
testem.js
tests/.eslintrc.js
tests/acceptance/admin-test.js
tests/acceptance/appointments-test.js
tests/acceptance/custom-forms-test.js
tests/acceptance/imaging-test.js
tests/acceptance/incident-test.js
tests/acceptance/inventory-test.js
tests/acceptance/invoices-test.js
tests/acceptance/labs-test.js
tests/acceptance/language-select-test.js
tests/acceptance/login-test.js
tests/acceptance/medication-test.js
tests/acceptance/navigation-test.js
tests/acceptance/operative-test.js
tests/acceptance/outpatient-test.js
tests/acceptance/patient-notes-test.js
tests/acceptance/patients-test.js
tests/acceptance/pricing-test.js
tests/acceptance/procedure-test.js
tests/acceptance/role-test.js
tests/acceptance/users-test.js
tests/acceptance/visit-test.js
tests/helpers/run-with-pouch-dump.js
tests/test-helper.js
yarn.lock

This PR simplifies the asynchronous test code by replacing `andThen()` blocks with `async/await`
/cc @tangollama @stukalin

Convert test code to use async/await

---

app/invoices/edit/controller.js
app/invoices/edit/template.hbs
app/models/billing-line-item.js
tests/acceptance/invoices-test.js

Fixes #1440.
This PR reverts the change to amountOwedChanged from 4b313ef. It had been changed from an observer to a computed property, but the property is never accessed anywhere so it doesn't get updated correctly.

Changed amountOwedChanged back to observer.

---

config/deprecation-workflow.js
package.json
yarn.lock

Fixes #1382. Fixes #1370.
- we're using our own version of `ember-validations`
- we don't need deprecations-workflow anymore

Own ember validations

---

README.md

- It seems that this project is using yarn as its main NPM packages manager. So it should reflect that in the README

Replace usage of npm to yarn

---

app/inventory/delete/controller.js
app/inventory/edit/template.hbs
app/inventory/transfer/template.hbs
tests/acceptance/inventory-test.js

Fixes one of the bugs in #1439, next PR will fix the other one.
The inventory/edit page lets you delete any inv-location that has 0 units assigned. But deleting this (through a modal dialog and inventory/delete) doesn't persist the inv-location's parent inventory model, so the inventory model's 'locations' property still contains a reference to the inv-location you deleted.
It's OK if you click "Update" on inventory/edit after you perform the deletion, but if you just delete and click "Return", you'll break the inventory model and you won't be able to view it anymore, and also break inventory/listing.
This PR sends an "update" action on inventory/edit controller automatically after an inv-location is deleted.

Fix for deleting inv-location

---

.travis.yml
Dockerfile

- Replaced the usage of `npm` with `yarn` in Docker to improve build performance.

perf(docker): add `yarn` for faster dependency installs

---

package.json
public/index.html
public/manifest.json
src/__tests__/patients/patients-slice.test.ts
src/i18n.js
src/index.tsx
src/locales/en-US/translation.json

fix #1711 
- adds pwa support
- adds quick command to serve static assets from build folder
- updates manifest for better hospital run colors
- fixes translation not working because they were not being cached in the `/public` folder

feat(pwa): adds pwa support

---

src/__mocks__/i18next.js
src/__tests__/HospitalRun.test.tsx
src/__tests__/page-header/useTitle.test.tsx
src/__tests__/patients/GeneralInformation.test.tsx
src/__tests__/patients/edit/EditPatient.test.tsx
src/__tests__/patients/new/NewPatient.test.tsx
src/__tests__/patients/patient-slice.test.ts
src/__tests__/patients/patients-slice.test.ts
src/__tests__/patients/related-persons/RelatedPersons.test.tsx
src/__tests__/patients/view/ViewPatient.test.tsx
src/__tests__/scheduling/appointments/Appointments.test.tsx
src/__tests__/scheduling/appointments/appointment-slice.test.ts
src/__tests__/scheduling/appointments/appointments-slice.test.ts
src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
src/patients/GeneralInformation.tsx
src/patients/patient-slice.ts
src/patients/patients-slice.ts
src/patients/view/ViewPatient.tsx
src/scheduling/appointments/appointment-slice.ts
src/scheduling/appointments/appointments-slice.ts

Fixes #1804 partially
- Add better coverage for `GeneralInformation` that tests both editable and non-editable functionality
- Cleanup and standardize component test code
- Add assertions for Thunk actions using mock store's `store.getActions()` as described here https://medium.com/@philihp/testing-a-redux-connected-component-with-thunk-actions-with-enzyme-41be4cc0bdce
- Standardized naming of Redux actions such as `getAppointmentStart` to `fetchAppointmentStart` so actions that fetch data are named `fetch` consistently
- Removed `i18n` log messages from test output
- Removed some warnings from test output, but not all

test(tests): improve coverage, fix issues and errors in tests, cleanup

---

package.json
src/__tests__/patients/view/ViewPatient.test.tsx
src/clients/db/AppointmentsRepository.ts
src/components/Sidebar.tsx
src/patients/appointments/AppointmentsList.tsx
src/patients/view/ViewPatient.tsx
src/scheduling/appointments/appointments-slice.ts

add an appointments tab to the patient view which shows appointments list for corresponding patient.
Uses same layout as patient list view and also implements fuzzy search
#1769  
- add new appointments tab
- allow fuzzy search

feat(AppointmentsList): add an appointments tab to the patient view

---

src/__tests__/scheduling/appointments/util/scheduling-appointment.util.test.ts
src/scheduling/appointments/util/scheduling-appointment.util.ts

fix #1853
Set appointment date label precision to minutes

fix(breadcrumb): set appointment date precision to minutes in breadcrumb

---

src/__tests__/page-header/ButtonToolBar.test.tsx
src/index.css
src/page-header/ButtonToolBar.tsx

fix #1852
Align buttons to the right in the toolbar

fix(button toolbar): align buttons to the right in the toolbar

---

src/locales/enUs/translations/scheduling/index.ts

scheduling/appointments/AppointmentDetailForm.tsx label for 'walk in' is trying to consume
scheduling.appointment.types.walkIn but the translation file lists 'walkUp'. I changed the
translation file to reflect the value 'walk in'

fix(./locales/enus/translations/scheduling/index.ts): changed 'Walk Up'

---

src/locales/enUs/translations/scheduling/index.ts

Delete appointment button no longer displays internationalization keys and instead reads correctly.
Fixes #1901 
- added "Delete Appointment" to localization file

fix(schedual button): fixed delete appointment button

---

src/patients/new/NewPatient.tsx

Fixes #1906 .
- Added top margin to save and cancel buttons on new Patient page
_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)_

fix(#1906): fixed button position

---

src/components/input/TextInputWithLabelFormGroup.tsx
src/patients/GeneralInformation.tsx

Fixes #1915 
- Given Name is now marked as required for new patient/ edit patient
_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)_

fix(#1915):  Mark Given Name as required for new/edit Patient

---

src/components/input/DatePickerWithLabelFormGroup.tsx
src/patients/diagnoses/AddDiagnosisModal.tsx

Added required fields to diagnosis name and date
Fixes #1926
- Added optional `isRequired` field to `DatePickerWithLabelFormGroup`
- Added `isRequired` to both fields in the `AddDiagnosisModal`

fix(patients): add required field label for diagnosis

---

src/locales/enUs/translations/patient/index.ts

Changed the spelling of the Add Diagnoses Button to Add Diagnosis for Issue Number 1929.
Fixes #1929

fix(patients): changed Add Diagnoses button to Add Diagnosis

---

src/components/input/DateTimePickerWithLabelFormGroup.tsx
src/scheduling/appointments/AppointmentDetailForm.tsx

Fixes #1916.
Marked required fields with the *.
The following fields are required:
Patient
Start Date
End Date

fix(scheduling): mark required fields in New Appointment/Edit Appointment

---

src/__tests__/patients/allergies/Allergies.test.tsx
src/__tests__/patients/diagnoses/Diagnoses.test.tsx
src/__tests__/patients/new/NewPatient.test.tsx
src/__tests__/patients/related-persons/RelatedPersons.test.tsx
src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
src/__tests__/scheduling/appointments/view/ViewAppointment.test.tsx
src/locales/enUs/translations/actions/index.ts
src/locales/enUs/translations/patient/index.ts
src/locales/enUs/translations/patients/index.ts
src/locales/enUs/translations/scheduling/index.ts
src/patients/allergies/Allergies.tsx
src/patients/allergies/NewAllergyModal.tsx
src/patients/diagnoses/Diagnoses.tsx
src/patients/edit/EditPatient.tsx
src/patients/new/NewPatient.tsx
src/patients/related-persons/RelatedPersonTab.tsx
src/scheduling/appointments/new/NewAppointment.tsx
src/scheduling/appointments/view/ViewAppointment.tsx

Added some missing translations.
Note: In the Adding a new related person, there were two identical toasts. I removed one of them.

fix(translations): missing translations values

---

src/__tests__/patients/GeneralInformation.test.tsx
src/__tests__/patients/new/NewPatient.test.tsx
src/components/input/TextInputWithLabelFormGroup.tsx
src/locales/enUs/translations/patient/index.ts
src/locales/ptBr/translations/patient/index.ts
src/patients/GeneralInformation.tsx
src/patients/edit/EditPatient.tsx
src/patients/new/NewPatient.tsx

feat(patient): provide better feedback on patient form

---

src/__tests__/patients/allergies/NewAllergyModal.test.tsx
src/locales/enUs/translations/patient/index.ts
src/patients/allergies/NewAllergyModal.tsx

Fixes [#1924.](https://github.com/HospitalRun/hospitalrun-frontend)

feat(patients): better form feedback for add allergy

---

src/__tests__/components/Navbar.test.tsx
src/__tests__/components/Sidebar.test.tsx
src/components/Navbar.tsx
src/components/Sidebar.tsx
src/locales/enUs/translations/patients/index.ts
src/locales/enUs/translations/scheduling/index.ts

Fixes #1857
- Added two sublinks to Patients link
- One to display Patients List, the other one to display Patient Creator Module
- Added two sublinks to Appointment link
- One to display Schedule and the other one to display the Appointment Generator module
- New added links are highlighted when these modules are displaying
- Links at the top navigation bar disappear when the `Sidebar` is available, otherwise, they'll show up.
- Added expansion UI dynamics to the Patients and Appointments link

feat: Added new proposed links to the sidebar

---

src/__tests__/patients/list/Patients.test.tsx
src/locales/enUs/translations/patient/index.ts
src/patients/list/Patients.tsx

- change the patient list to a table

feat(patients): refactor patient list to use table

---

src/__tests__/patients/related-persons/RelatedPersons.test.tsx
src/locales/enUs/translations/actions/index.ts
src/patients/related-persons/RelatedPersonTab.tsx

Fixes #1768.
- refactored related person list to be a table
- added ability to remove related person

feat(patients): adds ability to remove related person

---

src/locales/enUs/translations/scheduling/index.ts

Fixes #[[1996](https://github.com/HospitalRun/hospitalrun-frontend/issues/1996)].
- Added missing scheduling.appointments.editAppointment label
- Added missing scheduling.appointments.deleteAppointment label

fix(breadcrumb label): edit Appointment label on breadcrumb

---

.github/CONTRIBUTING.md
.gitpod.yml
README.md

Hi! 
This Pr enhances Gitpod setup it updates the config so that on the workspace startup Gitpod should pre-install all the dependencies and start the webserver. 
I have also added some description about it in the README and CONTRIBUTING.md so that people who are interested in contributing can benefit from Gitpod and start coding straight away without any friction in a single-click.
You can give the enhanced setup a try on my fork of the repo via this link:
https://gitpod.io/#https://github.com/nisarhassan12/hospitalrun-frontend
This is how it looks:

ci(gitpod): enhance gitpod setup.

---

src/__tests__/patients/list/ViewPatients.test.tsx
src/patients/list/ViewPatients.tsx

fix #2043
- Remove redundant db call in `ViewPatients`
- Add test case

fix(viewpatients): call PatientRepository.findAll() only once

---

src/index.css

**Styling the Navbar to make it Sticky so as to cover the Empty Top-Left Corner of the Webpage after Scrolling**
**Fixes this [issue](https://github.com/HospitalRun/hospitalrun/issues/319).**
**Styling the Navbar to make it Sticky**
**Before Making the Navbar Sticky the Top-Left corner looks something like this on Scrolling:**
**After Making the Navbar Sticky the Top-Left corner looks something like this on Scrolling:**

fix: styling the Navbar to make it Sticky

---

src/__tests__/labs/lab-slice.test.ts
src/__tests__/labs/requests/NewLabRequest.test.tsx
src/labs/lab-slice.ts
src/model/Lab.ts

Add new field `requestedBy` into the model. 
The field is auto filled by system when a new lab request is created.
The new field will contain the user id of the current user
fix #2082
- add field to model
- update request lab action to fill the filed
- update tests

feat(labs): add requestedby to new laboratory request

---

src/incidents/view/ViewIncident.tsx

fix #2081
- Added loading text until the incident if fetched

fix(incidents): add loading during fetch phase

---

src/__tests__/components/Navbar.test.tsx
src/components/Navbar.tsx
src/pageMap.tsx
src/user/user-slice.ts

Fixes #2117.
- Navbar becomes bare minimum when Sidebar goes away at a certain browser width.
- Add a hamberger menu for the bare minimum version, with the same menu items as the Sidebar.
**Please note:**
Some updates are wanted in the Components repo later.
- Link list can display an icon and a text
- Link list can show a divider
- Use Font Awesome's [bars icon](https://fontawesome.com/icons/bars)

fix(navbar): Make Navbar mobile-friendly

---

.eslintrc.js
.github/PULL_REQUEST_TEMPLATE.md

- turns of `@typescript-eslint/explicit-module-boundary-types` to remove warnings occurring in linting process. This rule is similar to other requirements for not needing a return type on functions that we have already turned off.

chore(lint): turn off @typescript-eslint/explicit-module-boundary-types

---

.eslintrc.js
src/__tests__/incidents/list/ViewIncidents.test.tsx
src/__tests__/labs/ViewLabs.test.tsx
src/__tests__/patients/care-plans/CarePlanTable.test.tsx
src/__tests__/patients/labs/LabsTab.test.tsx
src/__tests__/patients/list/ViewPatients.test.tsx
src/__tests__/patients/related-persons/RelatedPersonsTab.test.tsx
src/incidents/list/ViewIncidents.tsx
src/labs/ViewLabs.tsx
src/patients/care-plans/CarePlanTable.tsx
src/patients/labs/LabsTab.tsx
src/patients/list/ViewPatients.tsx
src/patients/related-persons/RelatedPersonTab.tsx
src/shared/components/input/TextFieldWithLabelFormGroup.tsx
src/shared/db/IncidentRepository.ts
src/shared/db/Repository.ts
src/shared/locales/enUs/translations/actions/index.ts

- refactor tables to use Table component
- fixed an issue with labs table not displaying results
- fixed an issue with incidents table not displaying results

refactor: use Table component

---

src/labs/ViewLabs.tsx

- minor fix, update hardcoded text to support localization
- No new dependencies added
P.S. As far as I understood placeholder always shadowed by input value, so I decided to hold the same text in label and placeholder. If it's not ok, I'll add new locale variable =)

fix: update hardcoded text with i18n locales

---

src/shared/components/navbar/Navbar.tsx
src/shared/locales/enUs/translations/actions/index.ts

Add the translation key for 'logout' in
_src/shared/locales/translations/actions_ folder and made the appropriate
changes where the 'logout' text appears (like in navbar)
✅ Closes: #2188

fix(bug) add the translation key for 'logout'

---

src/shared/components/navbar/Navbar.tsx

Fixes #2210 
- Fixed weird spacing issue in quick add icon
- No new dependencies added

fix: weird spacing issue in quick add icon

---

src/__tests__/shared/components/navbar/Navbar.test.tsx
src/shared/components/navbar/Navbar.tsx
src/shared/components/navbar/pageMap.tsx

fix #2208 
- add type check for icons
- add icon properties in page object
- add icon to each item in 'quick add' navbar item
**No new dependency added**

feat(navbar): add icons to 'quick add' icon in navbar

---

src/__tests__/shared/components/navbar/Navbar.test.tsx
src/shared/components/navbar/Navbar.tsx
src/shared/locales/enUs/translations/user/index.ts

Fixes #2225 .
- add ability to display user name in profile dropdown
- add ability to navigate to the setting route
- add new test for display user name 
- add translation key to display profile message
**No new dependency added**

feat(navbar): display currently logged in user name

---

src/__tests__/labs/requests/NewLabRequest.test.tsx
src/labs/requests/NewLabRequest.tsx
src/shared/locales/enUs/translations/labs/index.ts

fix #2296
- Rename `New Lab Request` button to `Request Lab` in sidebar and quickAdd (Navbar)
- Rename `Save` button to `Request` in the new lab request page

refactor(lab): rename lab request related buttons

---

src/shared/components/navbar/Navbar.tsx

Fixes #2306 
- Remove duplicated link from navbar quick create menu
NONE

fix(navbar): removed duplicate Report Incident link from quick create menu

---

src/__tests__/patients/appointments/AppointmentsList.test.tsx
src/__tests__/patients/hooks/usePatientAppointments.test.tsx
src/patients/appointments/AppointmentsList.tsx
src/patients/hooks/usePatientAppointments.tsx
src/scheduling/appointments/appointments-slice.ts

Fixes: #2341 
- add new hook `usePatientAppointments` and supporting tests
- Update `AppointmentsList` to use `usePatientAppointments` hook and update supporting tests
- Remove no longer used `fetchPatientAppointments`

refactor(patient): refactor patient appointments to use react query

---

src/shared/components/navbar/Navbar.tsx
src/shared/components/navbar/pageMap.tsx

The corrects the issue #2326
https://github.com/HospitalRun/hospitalrun-frontend/issues/2326
Fixes #2326
- Reordered the navigation menu items

fix(navigation): align quick menu with sidebar and mobile version

---

src/patients/care-plans/CarePlanTable.tsx

Fixes #2372
- add t() function invoking on key actions.view(available for enUS translations)
NONE

fix(care plan): fix view button label in list

---

src/index.css

No issue is opened for this
- Currently, bootstrap position was given more importance instead of .navbar style in index.css.
- The style in our repository was made more important by adding additional class (navbar-dark), so it gets weightage. (and navbar-dark is theme, so we do not need to worry)
- None

fix(navbar): navbar is now sticky

---

src/dashboard/Dashboard.tsx
src/imagings/requests/NewImagingRequest.tsx
src/imagings/search/ViewImagings.tsx
src/incidents/list/ViewIncidents.tsx
src/incidents/report/ReportIncident.tsx
src/incidents/visualize/VisualizeIncidents.tsx
src/labs/ViewLabs.tsx
src/labs/requests/NewLabRequest.tsx
src/medications/requests/NewMedicationRequest.tsx
src/medications/search/ViewMedications.tsx
src/patients/new/NewPatient.tsx
src/patients/search/ViewPatients.tsx
src/scheduling/appointments/ViewAppointments.tsx
src/settings/Settings.tsx

unable to update componenets , which are using updateTitle to set
the label of the page.
Fixes #2417.
- Add updateTitle(t('label')) into effect hook(useEffect).

fix: resolve TitleProvider warnings logged in the browser console

---

src/patients/view/ImportantPatientInfo.tsx

Fixes #[2438](https://github.com/HospitalRun/hospitalrun-frontend/issues/2438).
-  Fixed the "Add Visit" button container height so that the button doesn't grow to fit the container
NONE

fix(patientview): add visit button height fix

---

src/__tests__/shared/utils/formatDate.test.ts
src/patients/search/ViewPatientsTable.tsx
src/patients/view/ImportantPatientInfo.tsx
src/shared/util/formatDate.ts

Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/2439
- add formatDate helpers
- add tests for formatDate helper
- use formatDate in components, mentioned in the issue (ViewPatientsTable, ImportantPatientInfo)
- no new dependencies

refactor(patients): Improve date format consistency

---

src/shared/model/Diagnosis.ts

Fixes #2463 
- fixed typo of "remission"
Attached screenshot

fix(i18n): fixed typo of remission text

---

src/__tests__/patients/appointments/AppointmentsList.test.tsx
src/__tests__/patients/view/ViewPatient.test.tsx
src/patients/appointments/AppointmentsList.tsx
src/patients/view/ViewPatient.tsx
src/scheduling/appointments/new/NewAppointment.tsx

Fixes #2350 .
- Passing patient to `NewAppointment` through `history.push` and accessing it using `useLocation`
- Using this prop as the default in `AppointmentDetailForm`
None

feat: auto populate patients

---

src/__tests__/patients/util/validate-patient.test.ts
src/patients/patient-slice.ts
src/patients/util/validate-patient.ts

This change is an intermediate step to solve #2378, #2382.
- Create a shared patient validator to be able to use on different hooks

refactor(patient): decouple patient validator from redux code

---

src/imagings/search/ViewImagings.tsx
src/incidents/list/ViewIncidents.tsx
src/labs/ViewLabs.tsx
src/medications/search/MedicationRequestSearch.tsx
src/medications/search/ViewMedications.tsx

Medications, Labs, Imagings, and Incidents search views made consistent with @hospitalrun/components
Fixes #2503. 
- Medications search view component changed to common style using components from `@hospitalrun/components`
- Labs search view component changed to common style using components from `@hospitalrun/components`
- Imagings search view component changed to common style using components from `@hospitalrun/components`
- Incidents search view component changed to common style using components from `@hospitalrun/components`
_-None-_
_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your …

fix: search views width inconsistency

---

src/shared/locales/enUs/translations/medications/index.ts

Fixes #2495 (i85n enUs locale spelling of 'canceled')
- Changed spelling of _"cancelled"_ to _"canceled"_ in the `src/shared/locales/enUs/medications/index.ts` file.
-None-
_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)_

fix(medications): enUs locale spelling of canceled

---

src/__tests__/labs/requests/NewLabRequest.test.tsx
src/labs/requests/NewLabRequest.tsx
src/shared/model/Lab.ts

Add functionality to link visit to lab, and updated the schema to have a visitId in the Lab model.
fix #2184
Fixes #2184.
- Updated Lab db model to have an optional `visitId`
- In the "New Lab Request" screen, added a required dropdown to associate the lab request with a visit id.

feat(lab): link visit to labs

---

src/__tests__/labs/requests/NewLabRequest.test.tsx
src/labs/requests/NewLabRequest.tsx

Fixes #2551 .
- I make the `NewLabRequest` use the exact same method to solve the `null` visit issue. [`NewImagingRequest.tsx` line65](https://github.com/HospitalRun/hospitalrun-frontend/blob/45647d3b4a15ca8d9c57ebda66b3712658d62f19/src/imagings/requests/NewImagingRequest.tsx#L65)
- My concern is, we use the `as Option[]` at line 57. So that the type of the variable `visits` is not right. It should be `Option[] | null`. Maybe we should do some refactor in `NewImagingRequest.tsx` and `NewLabRequest.tsx` to fix this wrong type. Otherwise, it may lead to other bugs in the future.

fix(lab): In New lab request make the visit field required

---

src/__tests__/patients/view/ViewPatient.test.tsx
src/__tests__/patients/visits/VisitTable.test.tsx
src/patients/hooks/usePatientVisits.tsx
src/patients/view/ViewPatient.tsx
src/patients/visits/VisitTable.tsx
src/shared/locales/enUs/translations/patient/index.ts

Fixes #2563 
**Note:** The bug was initially reported for the patient **visits tab**, but I realized that the same bug was also happening in the tabs: **allergies, notes, care-plans, care-goals**. Fixed all of them.
**Why the bug happened?**
When someone visits one of the mentioned tabs and, for example, clicks an element to view it, and it opens in a nested route, then the tab loses the active status because the route path changed.
- fix: Keep corresponding tabs as active for nested routes
- Add missing warning alert in visits table (attached screenshots)
Warning alert before (shows empty table):
Warning alert after:

fix(viewpatient): keep tabs active for nested routes

---

src/__tests__/patients/history/HistoryTab.test.tsx
src/__tests__/patients/history/HistoryTable.test.tsx
src/__tests__/patients/history/mappers/HistoryRecordsMapper.test.tsx
src/__tests__/patients/history/mappers/helpers.test.tsx
src/__tests__/patients/view/ViewPatient.test.tsx
src/patients/history/HistoryTab.tsx
src/patients/history/HistoryTable.tsx
src/patients/history/mappers/HistoryRecordsMapper.tsx
src/patients/history/mappers/helpers.tsx
src/patients/view/ViewPatient.tsx
src/shared/locales/enUs/translations/patient/index.ts
src/shared/model/PatientHistoryRecord.tsx

Fixes #2255 
- Add a new history tab for patient's view
- Currently support only histories for Lab and Appointment
- History for a Lab can be one in three types of events: Requested, Canceled and Completed
- History for an Appointment can be one in two types of events: Started or Ended
- History events are sorted in descending order, i.e the latest event should be on the top

feat: Add patient history tab
