CONTRIBUTING.md

Files were added into directory `engineering/`

Update styleguide links in CONTRIBUTING.md

---

prod/robots.txt
public/robots.txt

- Add a comment making it clear to everyone that the directives from the robots.txt file allow all content on the site to be crawled

Prevent all robots from scanning the site

---

app/styles/_sign_in_screen.scss

Related to https://github.com/HospitalRun/hospitalrun-frontend/pull/226

Use percentages for sign in modal centering

---

README.md
app/controllers/login.js
app/styles/_sign_in_screen.scss
app/templates/login.hbs
tests/acceptance/login-test.js

Glad for any feedback, this one seems pretty straightforward though.

Issue #250: Provide feedback on failed login

---

CONTRIBUTING.md

Adds some details to the CONTRIBUTING doc to help clarify best practices for opening a pull request. Also modified doc heading structure.
cc @jkleinsc @tangollama

Add guidelines for submitting a pull request

---

CONTRIBUTING.md

Removes an extra bullet added accidentally in #254 causing formatting issues.

Fix CONTRIBUTING formatting

---

app/styles/_sidebar_nav.scss

Most noticable with the administration icon

Center side navigation icons

---

README.md

cc @HospitalRun/core-maintainers for FYI.

Add some troubleshooting tips to README

---

app/locales/ru/translations.js

Feel free to ping me when localization base will expand.

Add russian localization

---

app/locales/tr/translations.js

Added Turkish localization file

Added Turkish localization

---

app/locales/fr/translations.js

I have translated the strings available in the translations.js file for the french language. Please note that you did not make all the strings available so that we do a complete translation.

Added french translation

---

app/services/database.js

Propagate the error out when loading DB fails

---

.scss-lint.yml

Change lint severity from warning to error

---

app/styles/_base.scss

Resolves a handful of scss-lint errors introduced with #372.

Resolve lint errors

---

app/imaging/index/template.hbs
app/inventory/listing/template.hbs
app/invoices/index/template.hbs
app/labs/index/template.hbs
app/medication/index/template.hbs
app/patients/edit/template.hbs
app/patients/index/template.hbs
app/pricing/index/template.hbs
app/pricing/profiles/template.hbs
app/styles/_base.scss
app/styles/_bootstrap-theme.scss
app/styles/_bootstrap.scss
app/styles/app.scss
app/styles/components/_form_styles.scss
app/styles/components/_patient_summary.scss
app/styles/components/_tab_content.scss
app/styles/components/_tab_nav.scss
app/templates/charges-by-type.hbs
app/templates/components/patient-summary.hbs
app/users/index/template.hbs
tests/acceptance/appointments-test.js
tests/acceptance/patients-test.js

Form cleanup first pass

---

app/styles/_variables_mixins.scss
app/styles/app.scss
app/styles/components/_sidebar_nav.scss

Makes some small design tweaks to the sidebar nav including:
- remove border from sub items and reduce vertical size
- add subtle hover animations
- add hover effect to logo

Nav design tweaks

---

app/labs/completed/route.js
app/labs/completed/template.hbs
app/labs/delete/controller.js
app/labs/delete/template.hbs
app/labs/edit/controller.js
app/labs/edit/route.js
app/labs/edit/template.hbs
app/labs/index/route.js
app/labs/index/template.hbs
app/labs/route.js
app/locales/en/translations.js

Got a chance to hammer this out tonight.
Fixes #279.
- add localization support for labs module
- add EN translation for labs module localization
Added english translation for labs

i18n add localization support for labs module closes #279

---

.github/PULL_REQUEST_TEMPLATE.md

We are still getting lots of pull requests with unformatted and unhelpful descriptions. Perhaps the template content is unclear. This PR helps to address that.
- clarify the referenced issue number line
- add placeholder items to proposed changes
- add a note clarifying purpose

Update PULL_REQUEST_TEMPLATE.md to be more clear

---

app/labs/edit/template.hbs

Fixes #.
- Added proper translations for field Lab Type, Result, and Notes in the Labs module.

Fixed missing translation in the Labs module

---

app/locales/en/translations.js
app/patients/add-contact/controller.js
app/patients/add-contact/template.hbs
app/patients/delete/controller.js
app/patients/delete/template.hbs
app/patients/edit/controller.js
app/patients/edit/route.js
app/patients/imaging/template.hbs
app/patients/index/route.js
app/patients/index/template.hbs
app/patients/labs/template.hbs
app/patients/medication/template.hbs
app/patients/notes/controller.js
app/patients/photo/controller.js
app/patients/quick-add/controller.js
app/patients/quick-add/template.hbs
app/patients/reports/controller.js
app/patients/reports/route.js
app/patients/reports/template.hbs
app/patients/route.js
app/patients/socialwork/expense/controller.js
app/patients/socialwork/expense/template.hbs
app/patients/socialwork/family-info/controller.js
app/patients/socialwork/family-info/template.hbs

Fixes #[https://github.com/HospitalRun/hospitalrun-frontend/issues/274].
Translates the patients module

Translate patients

---

app/invoices/add-line-item/template.hbs
app/invoices/delete/template.hbs
app/invoices/edit/template.hbs
app/invoices/index/template.hbs
app/invoices/payment/template.hbs
app/locales/en/translations.js
app/pricing/delete/template.hbs
app/pricing/edit/template.hbs
app/pricing/index/template.hbs
app/pricing/override/template.hbs
app/pricing/profiles/template.hbs
app/pricing/search/template.hbs
tests/acceptance/invoices-test.js
tests/acceptance/pricing-test.js

cherry picked version of https://github.com/HospitalRun/hospitalrun-frontend/pull/479

Translate billing 2

---

app/admin/loaddb/controller.js

- simple PR to remove unused space

Remove unused space

---

.github/CONTRIBUTING.md

- Spelling and grammar
Pretty simple!

Documentation: Small edits to Contribute

---

app/locales/en/translations.js
app/procedures/charge/controller.js
app/procedures/charge/template.hbs
app/procedures/edit/controller.js
app/procedures/edit/route.js
app/procedures/edit/template.hbs
app/procedures/medication/controller.js
app/procedures/medication/template.hbs

Fixes #[replace brackets with the issue number that your pull request addresses].
- [list out summary of changes here]
- [list out summary of changes here]
- [list out summary of changes here]
- [etc]

Translate procedures

---

.stylelintrc

Groups stylelint rules by type. as their documents recommend
should we order alphabetically ?

Group stylelint rules by type

---

app/locales/en/translations.js

Required strings for ember-validations to be translated as well 👍 

Add translations for ember-validations

---

app/locales/en/translations.js
app/print/invoice/template.hbs

Translates invoices. currently ignoring the template because we aren't translating specific to hospital strings.

Translate printed invoice

---

app/appointments/delete/template.hbs
app/appointments/edit/route.js
app/appointments/edit/template.hbs
app/appointments/index/route.js
app/appointments/route.js
app/appointments/search/route.js
app/appointments/today/route.js
app/locales/en/translations.js
app/locales/es-CO/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/medication/completed/route.js
app/medication/delete/template.hbs
app/medication/edit/controller.js
app/medication/edit/route.js
app/medication/index/route.js
app/medication/index/template.hbs
app/medication/return/controller.js
app/medication/return/route.js
app/medication/return/template.hbs
app/medication/route.js

Fixes #584 and #585.
- The start of changing Translation keys from _ standard to camel case to work with JavaScript convention.

Fixes issues 584 and 585

---

.template-lintrc.js
app/admin/query/template.hbs
app/imaging/delete/template.hbs
app/locales/en/translations.js
package.json

Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/491
Part Of https://github.com/HospitalRun/hospitalrun-frontend/issues/490
Installed ember-cli-lint, to lint for bare strings

Install ember-cli-template-lint

---

app/inventory/barcode/controller.js

Fixes #458 .
- Fixes incorrect dependent keys on barcodeUri that was preventing the property from being recomputed.

Issue 458: Fixed incorrect dependent keys on barcode.

---

app/models/invoice.js

Fixes #467.
Please take a look at [this comment](https://github.com/HospitalRun/hospitalrun-frontend/issues/467#issuecomment-247857012) for details.

Mark an invoice as paid only when the payments have been saved

---

.template-lintrc.js
app/inventory/edit/template.hbs
app/templates/components/array-display.hbs
app/templates/login.hbs

To improve quality of code, i am enabling:
- self-closing-void-elements
- html-comments
details of these rules can be found here : https://github.com/rwjblue/ember-template-lint

enable self-closing-void-elements and html-comments

---

app/admin/roles/controller.js
app/components/checkbox-or-typeahead.js
app/components/inventory-location-picker.js
app/controllers/abstract-edit-controller.js
app/helpers/is-equal-array.js
app/inventory/reports/controller.js
app/mixins/user-session.js

Fix `contains` deprecations
http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains

contains has been deprecated in favour of includes

---

tests/acceptance/appointments-test.js

`a+b` -> `a + b`
Part of #732.

[Cleanup] eslint `space-infix-ops`

---

app/admin/lookup/controller.js
app/components/custom-form.js
app/locales/de/translations.js
app/locales/en/translations.js
app/locales/es-CO/translations.js
app/locales/es/translations.js
app/locales/fr/translations.js
app/locales/pt-BR/translations.js
app/locales/ru/translations.js
app/locales/tr/translations.js
app/procedures/medication/controller.js

`{ age:21 }` -> `{ age: 21 }`
Part of #732.

[Cleanup] eslint `key-spacing`

---

tests/acceptance/inventory-test.js

Fixes #693 
Add test for inventory.barcode, check the exist of barcode image.

Add test for inventory.barcode, closes #693

---

app/locales/en/translations.js
app/locales/es-CO/translations.js
app/locales/es/translations.js

[Cleanup] eslint `quotes`

---

README.md

Use Oxford comma

---

app/admin/loaddb/controller.js
app/appointments/search/controller.js
app/inventory/batch/controller.js
app/inventory/edit/controller.js
app/inventory/reports/controller.js
app/inventory/request/controller.js
app/invoices/edit/controller.js
app/medication/edit/controller.js
app/medication/edit/route.js
app/mixins/charge-actions.js
app/mixins/patient-submodule.js
app/models/invoice.js
tests/helpers/authenticate-user.js

Consistent indentation (2 spaces)
Part of #732.

[CLEANUP] eslint `indent`

---

.github/CONTRIBUTING.md

Adds a section on Tests to the Contributing file.

Update CONTRIBUTING.md to add a section about tests

---

.eslintrc.js
tests/.eslintrc.js

This was supposed to happen when #732 was completed, but some parts take a significant amount of time.
Should be merged after #808 #809 and #810.

Enable `ember-suave`

---

tests/unit/utils/email-validation-test.js

- Add `EmailValidation.emailRegex` unit tests

Add EmailValdition unit tests

---

tests/unit/models/add-diagnosis-test.js

- Add model unit test for add-diagnosis

Add model unit test for add-diagnosis

---

tests/unit/models/family-info-test.js
tests/unit/models/imaging-test.js

- Add model unit test family-info
- Add model unit test imaging

Add model unit tests imaging & family-info

---

app/locales/en/translations.js
app/patients/add-contact/controller.js

Fixes #852
- add translation for 'Add Patient Contact' on the form to add patient contact

add english translation for 'Add patient contact'

---

.github/CONTRIBUTING.md

Fixes #375.
- The CONTRIBUTING.md has been updated with the description and usage of "Linters"
- Links to linter packages for common text editors has also been added.
Thanks!

Added linter in CONTRIBUTING.md

---

tests/unit/models/invoice-test.js

- Add model unit test for invoice

Add model unit test for invoice

---

tests/unit/models/medication-test.js

- Add model unit test for medication

Add model unit test for medication

---

tests/unit/models/patient-note-test.js

- Add model unit test for patient-note

Add model unit test for patient-note

---

tests/unit/models/payment-test.js

- Add model unit test for payment

Add model unit test for payment

---

tests/unit/models/user-test.js

- Add model unit test for user

Add model unit test for user

---

tests/unit/mixins/patient-diagnosis-test.js

- Add mixin unit test for patient-diagnosis

Add mixin unit test for patient-diagnosis

---

tests/unit/mixins/return-to-test.js

- Add mixin unit test for return-to

Add mixin unit test for return-to

---

app/locales/ur/translations.js

**Urdu Translation**
The file
`app/locales/ur/translations.js`
contains Urdu translation of 
`app/locales/en/translations.js`
As of now, the files are up to date with latest commit on actual hospitalrun-frontend repo: e33ff61c8722b509c42aa2e4009b8abaa57a4e91
- Urdu Localization
**Files added or edited:**
`app/locales/ur/translations.js`

Add Urdu Locale (ur).

---

tests/acceptance/medication-test.js

Fixes #697 
- Add medication completed test

add medication completed test

---

ember-electron/electron-forge-config.js
package.json
yarn.lock

A few changes to the build process.

Ember build fixes

---

.github/CONTRIBUTING.md

Minor, but thought it'd be appropriate since HospitalRun is now using ember 2.10

Update links to 2.10 ember docs

---

app/patients/add-contact/controller.js

Fixes #1145.
- Set the fields to a blank string after add button is clicked

Add contact form clearance issue #1145

---

app/mixins/blood-types.js

Closes #1143.
- add additional blood sub-types

Add additional blood types

---

tests/acceptance/inventory-test.js
tests/acceptance/patients-test.js

Fixes #700.
- added patients search test in tests/acceptance/patients-test.js

Resolve issue 700

---

tests/acceptance/inventory-test.js

Fixes #695.
- added inventory-search test to tests/acceptance/inventory-test.js

added inventory-search test

---

tests/acceptance/invoices-test.js

Fixes #696 
- added test for invoices.search in test/acceptance/invoices-test.js

Resolve issue 696

---

.github/CONTRIBUTING.md

- Display the character string enclosed with <>

Update the path of translations.json in CONTRIBUTING.md

---

app/medication/search/route.js
tests/acceptance/medication-test.js

Fixes #698.
- added extra search fields to app/medication/search/route.js
- added search test to tests/acceptence/medication-test.js
- note you can still **not** search by patient-name

Added medication search fields and added a related test

---

app/styles/_bootstrap.scss

Fixes #1223 ].
Updated .scss file to enable viewing of end time for appointments.

New Appointment - For Clinic - End Time #1223

---

.stylelintrc

Fixes https://github.com/HospitalRun/hospitalrun-frontend/issues/1302

Change to selector-max-id

---

app/mixins/dob-days.js
tests/unit/mixins/dob-days-test.js

fix DOB unit tests
Fixes #1294.
- fix and improving readability of DOB formatting unit tests
- fix date parsing

address #1294: fix DOB unit tests

---

README.md

Fixes markdown highlighting in setup description.
- Markdown highlight in README.md

Fix markdown highlighting in README

---

package.json
tests/ember-electron/main.js

Closes #1258 .
- `ember-electron` is now on the latest version
- blueprint generator was run once again --> some updates/dependencies were installed
- `main.js` was replaced with the one from the blueprint

Greenkeeper/ember electron 2.7.2

---

Dockerfile
README.md
docker-compose.yml

- fix Dockerfile since alpine doesn't have many required packages
- enable autoreloading via docker-compose
- readme fix
Somehow #1300 brought issues in Docker container building which were not identified right away (very-very strange). Proposed is the fix for that.

Docker fix

---

app/locales/translations

Thailand translations update
admin/{address,customForms} TH translations

Thai translations

---

package.json

chore(package): update electron-forge to version 5.1.1

---

Dockerfile
script/initcouch.sh
script/initcouch2.sh

Fixes #988. (hopefully)
- fixed `Dockerfile` after moving to the js scripts
- fixed shebang

fix docker for windows

---

app/locales/he/config.js
app/locales/he/translations.js

Fixes (No Issue was open)
- added Hebrew translation including a config with rtl attribute set to true

Add Hebrew translation

---

app/locales/ur/config.js
app/services/language-preference.js
app/styles/_base.scss
app/styles/_variables_mixins.scss
app/styles/components/_panel.scss
app/styles/components/_sidebar_nav.scss
app/utils/locale-utils.js

Fixes #1247 
- Add config file with 'rtl' attribute to urdu language
Note: I don't think this solves all the problems, since rtl support needs to be enabled as integral part of the styling system, including rtl direction, opposite floating and alignment, etc.

Added RTL layout/style support + Fixed added 'rtl' property to urdu

---

package.json
tests/acceptance/admin-test.js
tests/acceptance/appointments-test.js
tests/acceptance/custom-forms-test.js
tests/acceptance/imaging-test.js
tests/acceptance/incident-test.js
tests/acceptance/inventory-test.js
tests/acceptance/invoices-test.js
tests/acceptance/labs-test.js
tests/acceptance/language-select-test.js
tests/acceptance/login-test.js
tests/acceptance/medication-test.js
tests/acceptance/navigation-test.js
tests/acceptance/operative-test.js
tests/acceptance/outpatient-test.js
tests/acceptance/patient-notes-test.js
tests/acceptance/patients-test.js
tests/acceptance/pricing-test.js
tests/acceptance/procedure-test.js
tests/acceptance/role-test.js
tests/acceptance/users-test.js
tests/acceptance/visit-test.js
tests/helpers/scenarios/custom-forms.js
yarn.lock

see https://github.com/simplabs/qunit-dom
this will be the default way to do DOM assertions starting with Ember CLI 3.2

Use `qunit-dom` for DOM assertions

---

.github/CONTRIBUTING.md

http://cball.me/organize-your-ember-app-with-pods/ is dead. https://www.programwitherik.com/ember-pods/ is a pretty good explanation.
Fixes #[replace brackets with the issue number that your pull request addresses].
- replaces the pods explanation link with https://www.programwitherik.com/ember-pods/

Fix CONTRIBUTEING.md pods link

---

package.json

chore(package): update hospitalrun-dblisteners to version 1.0.4

---

app/locales/pt-br/translations.js

- Add translation to all undefined attributes in pt-br translation
- Fix some translations grammar
If some Portuguese speaker can review and find possible mistakes I would be grateful.

Sync and Fix Brazilian Portuguese Translation

---

app/incident/reports/controller.js
app/incident/reports/template.hbs
tests/acceptance/incident-test.js

Fixes #1527
- fixes issue with button styling on generate report button. Changes the styling from `btn btn-default` to `btn btn-primary` to match other buttons. 
- fixes issue with button styling on export report button. hanges the styling from `btn btn-default` to `btn btn-primary` to match other buttons. 
- fixes issue where click generate report resulted in `Error: Undefined`. This was fixed by changing `model=model` to `model=this` in the template file. Also, added `test-start-date` and `test-end-date` to the class for testing purposes. This is similar to how the start and end date pickers work in the inventory report. 

Fixes #1527

---

app/patients/reports/template.hbs

- changes export report button to btn-primary to match other export report buttons in the application 

fixes styling on patient export report button (changes from btn-defaullt to btn-primary

---

.editorconfig
.eslintignore
.eslintrc.js
.github/workflows/ci.yml
.travis.yml
.vscode/settings.json
azure-pipeline.yml
azure/azure-pipelines-npm.yml
azure/azure-pipelines-yarn.yml
package.json

Fixes #1623
- Adds Jest
- Adds Coveralls support

test(jest): adds jest

---

.eslintrc.js
.prettierrc
package.json
src/App.test.tsx
src/App.tsx
src/index.tsx

Fixes an issue with prettier + eslint configurations being duplciated in package.json and in configuration files.

style(lint): updates config files and linting rules

---

.eslintrc.js
package.json
public/locales/en/translation.json
src/components/Navbar.tsx

- chore(deps): bump @hospitalrun/components from 0.22.2 to 0.24.0
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 2.9.0 to 2.10.0
- chore(deps-dev): bump eslint-plugin-import from 2.18.2 to 2.19.1

dependency upgrades

---

src/patients/view/ViewPatient.tsx

- use panels to group content in view patient

feat(patients): use panels for grouping content in view patient

---

package.json
src/index.tsx

Fixes #1718 .
- import component library scss
** NOTE** Dependent on https://github.com/HospitalRun/components/pull/213

fix(scss): import scss from components library

---

.travis.yml
package.json

- fixes coveralls coverage report

Fixes coveralls coverage

---

src/patients/new/NewPatientForm.tsx

fix(patients): fix typo in classnames

---

src/__tests__/clients/db/PatientRepository.test.ts
src/clients/db/PatientRepository.ts

Fixes #1760.
- makes the patient search functionality case insensitive

fix(patients): makes patient search case insensitive

---

README.md

Improve `How to commit` section in README.md

docs(readme): improve "How to commit" section

---

.github/workflows/ci.yml
src/__tests__/patients/allergies/Allergies.test.tsx
src/__tests__/patients/allergies/NewAllergyModal.test.tsx
src/__tests__/patients/view/ViewPatient.test.tsx
src/locales/en-US/translation.json
src/model/Allergy.ts
src/model/Patient.ts
src/model/Permissions.ts
src/patients/allergies/Allergies.tsx
src/patients/allergies/NewAllergyModal.tsx
src/patients/util/timestamp-id-generator.ts
src/patients/view/ViewPatient.tsx
src/user/user-slice.ts

Fixes #1839
- adds the ability to add an allergy to a patient
- adds an `add:allergy` permission

feat(allergies): adds ability to add allergy to appointment

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/regression.md
.github/ISSUE_TEMPLATE/security.md

Add bug label by default to bug report and remove code snippets

chore(github): Add bug label by default to bug report and remove code snippets

---

src/__tests__/HospitalRun.test.tsx
src/__tests__/scheduling/appointments/util/scheduling-appointment.util.test.ts
src/scheduling/appointments/edit/EditAppointment.tsx
src/scheduling/appointments/util/scheduling-appointment.util.ts
src/scheduling/appointments/view/ViewAppointment.tsx

fix #1854
**Add the breacrumb into the Edit Appointment View**

fix(breadcrumb): add the breadcrumb for the edit appointment view

---

README.md

adding the call to action link in the readme to join the slack group

docs(readme): Add slack CTA

---

src/__tests__/patients/allergies/Allergies.test.tsx
src/__tests__/patients/diagnoses/AddDiagnosisModal.test.tsx
src/__tests__/patients/diagnoses/Diagnoses.test.tsx
src/__tests__/patients/view/ViewPatient.test.tsx
src/locales/en-US/translation.json
src/model/Diagnosis.ts
src/model/Patient.ts
src/model/Permissions.ts
src/patients/diagnoses/AddDiagnosisModal.tsx
src/patients/diagnoses/Diagnoses.tsx
src/patients/view/ViewPatient.tsx
src/user/user-slice.ts

Fixes #1838.
- adds ability to add and see diagnoses

feat(diagnoses): adds ability to add a diagnoses

---

package.json
src/__tests__/scheduling/appointments/AppointmentDetailForm.test.tsx
src/locales/en-US/translation.json
src/scheduling/appointments/AppointmentDetailForm.tsx

**Updated dependencies :**
- Updated react-scripts to version 3.4.0

Updated react-scripts to version 3.4

---

src/HospitalRun.tsx
src/__tests__/HospitalRun.test.tsx
src/__tests__/components/Sidebar.test.tsx
src/components/Sidebar.tsx
src/components/component-slice.ts
src/index.css
src/store/index.ts

Fixes #1858
- Made the sidebar bar collapsible.
- Made a minor css change regarding the sidebar style.
- Added a "components" state object in the RootState to manage sidebar's collapsible state. This can also be used in future to manage any other component's state like this sidebar.

feat: making sidebar collapsible

---

src/locales/enUs/translations/patient/index.ts

fix(#1899): added warning messages

---

CHANGELOG.md

Fix a typo in the changelog.md file

fix: typo in changelog.md

---

src/patients/related-persons/NewRelatedPersonModal.tsx

Fixes #1927 .
- add isRequired to Person Type field
- add isRequired to Relationship Type field
N/A

feat: indicate required fields in new Related Person Modal

---

.github/CONTRIBUTING.md
README.md

- refactored documentation to make setup process more clear
- added useful tools list
- add links back to main HospitalRun contributing doc
- removed duplicate information with main HospitalRun contributing doc

docs: updates documentation for better onboarding

---

.github/workflows/ci.yml
src/HospitalRun.tsx

- Add [this expression syntax](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions)

ci(github): add expression syntax to allow lint step to fail

---

src/__tests__/patients/related-persons/AddRelatedPersonModal.test.tsx
src/locales/enUs/translations/patient/index.ts
src/patients/related-persons/AddRelatedPersonModal.tsx

Fixes #1925 .
- adds related person form feedback
- adds relevant tests
shout out to @bmoore235 for getting the majority of this work done

feat(patients): add feedback to add related person form

---

src/locales/enUs/translations/patient/index.ts

Fixes #1993.
- Add translation for patient.Code

fix(patients): add translation for patient.Code

---

src/__tests__/HospitalRun.test.tsx
src/__tests__/page-header/ButtonBarProvider.test.tsx
src/__tests__/scheduling/appointments/new/NewAppointment.test.tsx
src/labs/ViewLab.tsx
src/labs/ViewLabs.tsx
src/labs/requests/NewLabRequest.tsx
src/locales/enUs/translations/scheduling/index.ts
src/patients/list/Patients.tsx
src/patients/view/ViewPatient.tsx
src/scheduling/appointments/Appointments.tsx
src/scheduling/appointments/new/NewAppointment.tsx
src/scheduling/appointments/view/ViewAppointment.tsx

Fixes #1960 
- fixes warnings in tests caused by update to other components not being done in a useEffect
- fixes some missing translations

fix: fixes warnings/errors appearing in console

---

src/locales/ptBr/translations/actions/index.ts
src/locales/ptBr/translations/index.ts
src/locales/ptBr/translations/labs/index.ts
src/locales/ptBr/translations/patient/index.ts
src/locales/ptBr/translations/patients/index.ts
src/locales/ptBr/translations/scheduling/index.ts

Fixes #1891.
- Translated everything from locales/enUs into Portuguese, put inside locales/ptBr

feat(localization): add portuguese language

---

.github/workflows/compressed-size.yml
package.json
src/__tests__/patients/GeneralInformation.test.tsx
src/__tests__/patients/edit/EditPatient.test.tsx
src/__tests__/patients/patient-slice.test.ts
src/locales/enUs/translations/patient/index.ts
src/patients/GeneralInformation.tsx
src/patients/patient-slice.ts

#1976.
- adds validation that the email and phone number are valid
- https://bundlephobia.com/result?p=validator@13.0.0

feat(patient): add email and phone number validation

---

src/__tests__/patients/appointments/AppointmentsList.test.tsx

Fixes #1836
- Added missing unit tests for AppointmentsList

test(appointments): add missing tests for AppointmentsList

---

src/components/input/DatePickerWithLabelFormGroup.tsx

Added year select dropdown to date picker (used for entering new patients' DOB)
Fix #2047.

feat(datepicker): add year selector dropdown

---

src/__tests__/components/Navbar.test.tsx
src/components/Navbar.tsx

Fixes #2099.
- Add a plus icon in the navbar. When clicked, it opens a list of links to pages where the user has a permission to create: patient, appointment, etc.

feat(navbar): add shortcut icon to the create pages

---

src/__tests__/patients/care-plans/AddCarePlanModal.test.tsx
src/__tests__/patients/care-plans/CarePlanForm.test.tsx
src/__tests__/patients/care-plans/CarePlanTab.test.tsx
src/__tests__/patients/care-plans/CarePlanTable.test.tsx
src/__tests__/patients/care-plans/ViewCarePlan.test.tsx
src/__tests__/patients/patient-slice.test.ts
src/__tests__/patients/view/ViewPatient.test.tsx
src/components/input/SelectWithLableFormGroup.tsx
src/locales/enUs/translations/patient/index.ts
src/model/CarePlan.ts
src/model/Patient.ts
src/model/Permissions.ts
src/patients/care-plans/AddCarePlanModal.tsx
src/patients/care-plans/CarePlanForm.tsx
src/patients/care-plans/CarePlanTab.tsx
src/patients/care-plans/CarePlanTable.tsx
src/patients/care-plans/ViewCarePlan.tsx
src/patients/patient-slice.ts
src/patients/view/ViewPatient.tsx
src/user/user-slice.ts

Fixes #2079 
- ability to view a list of care plans for a patient
- ability to add a care plan
- ability to view a care plan
** Things this PR does not attempt to address that will be addressed in a later PR **
- editing a care plan
- a nice view page for the care plan

feat(care plan): Add care plans to patients

---

.github/CONTRIBUTING.md

- adds note about making hospitalrun a public database.

docs: add note about making hospitalrun a public database

---

src/patients/related-persons/AddRelatedPersonModal.tsx
src/shared/hooks/useTranslator.ts

Fixes #2195.
- Conditionally call date-fns/format to format the date of birth, only if a date of birth value exists
None

fix(patients): fixes related person search crashing if no DoB

---

src/shared/components/Sidebar.tsx

- Changed the Incidents icon to the correct `incident` icon from components

fix: correct incident icon

---

.replit
README.md

- remove replit since it is unused and not maintained.

chore: remove replit

---

src/labs/requests/NewLabRequest.tsx
src/shared/locales/enUs/translations/labs/index.ts

Fixes #2293 
- Add **successfullyCreated** to `locales - enUs - labs`
- Update Toast success message

fix(lab request): Update Toast success message

---

src/patients/view/ImportantPatientInfo.tsx

Fixes #2443
- Using usePatientAllergies to refresh allergy data as new allergy is added.
None

fix(allergy): allergy data now gets refresh

---

src/patients/care-goals/CareGoalTable.tsx
src/shared/locales/enUs/translations/incidents/index.ts

Fixes #2534 #2535 
- fixed the translation in button label
- fixed the  labels on filter incidents
_Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)_

fix: button labels and status labels

---

.github/CONTRIBUTING.md

- Correct the couchdb cleanup scripts reference in contributing guide
NONE

docs(contributing) - fix cleanup scripts reference

---

src/__tests__/patients/care-goals/CareGoalTab.test.tsx

Fixes #2593
- Increased timeout allowed for the failed test from 30000 ms to 50000 ms.

Fix for issue #2593

---

package.json

Reverts HospitalRun/hospitalrun-frontend#2856

Revert "chore(deps-dev): bump @commitlint/cli from 15.0.0 to 16.0.0"

---

package.json

Reverts HospitalRun/hospitalrun-frontend#2859

Revert "chore(deps-dev): bump @commitlint/core from 15.0.0 to 16.0.0"

---

package.json

Reverts HospitalRun/hospitalrun-frontend#2858

Revert "chore(deps-dev): bump @commitlint/prompt from 15.0.0 to 16.0.0"
